version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: prisma-learn-postgres
    restart: always
    environment:
      POSTGRES_USER: prisma_user
      POSTGRES_PASSWORD: prisma_password
      POSTGRES_DB: prisma_learn_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U prisma_user -d prisma_learn_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
